Data Wrangling II 
Create an academic dataset and: 
• Handle missing values & inconsistencies  
• Identify outliers using any method (IQR / Z-score)  
• Apply data transformation (log, normalization, scaling)

In [1]:
import numpy as np
import pandas as pd

In [2]:
data={
    'Roll_no':range(1,11),
    'Name':['Ram','Sham','Pooja','Neha','Priya','Rohit','Manav','Gayatri','Sahil','khushi'],
    'DSBDA_score':[45,78,np.nan,67,66,87,132,36,np.nan,92],
    'OOP_score':[56,78,65,45,33,78,69,70,np.nan,65],
    'Attendance_count':[30,37,32,33,33,21,29,34,35,29]
}

In [3]:
df=pd.DataFrame(data)

In [4]:
df.to_csv('Academic_dataset.csv',index=False)

In [5]:
# load dataset
df=pd.read_csv('Academic_dataset.csv')
print(df.head())

   Roll_no   Name  DSBDA_score  OOP_score  Attendance_count
0        1    Ram         45.0       56.0                30
1        2   Sham         78.0       78.0                37
2        3  Pooja          NaN       65.0                32
3        4   Neha         67.0       45.0                33
4        5  Priya         66.0       33.0                33

In [6]:
print('Shape: ',df.shape)
print('\nDimension : ',df.ndim)
print('\nTotal number of elements : ',df.size)
print('\nData types: ',df.dtypes)

Shape:  (10, 5)

Dimension :  2

Total number of elements :  50

Data types:  Roll_no               int64
Name                 object
DSBDA_score         float64
OOP_score           float64
Attendance_count      int64
dtype: object

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Roll_no           10 non-null     int64
 1   Name              10 non-null     object
 2   DSBDA_score       8 non-null      float64
 3   OOP_score         9 non-null      float64
 4   Attendance_count  10 non-null     int64
dtypes: float64(2), int64(2), object(1)
memory usage: 528.0+ bytes
None

In [8]:
print(df.describe())

        Roll_no  DSBDA_score  OOP_score  Attendance_count
count  10.00000     8.000000   9.000000          10.00000
mean    5.50000    75.375000  62.111111          31.30000
std     3.02765    29.894756  15.036991           4.44847
min     1.00000    36.000000  33.000000          21.00000
25%     3.25000    60.750000  56.000000          29.25000
50%     5.50000    72.500000  65.000000          32.50000
75%     7.75000    88.250000  70.000000          33.75000
max    10.00000   132.000000  78.000000          37.00000

In [9]:
df.isnull().sum()

Roll_no             0
Name                0
DSBDA_score         2
OOP_score           1
Attendance_count    0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['DSBDA_score']=df['DSBDA_score'].fillna(df['DSBDA_score'].mean())
df['OOP_score']=df['OOP_score'].fillna(df['OOP_score'].mean())

In [12]:
df.isnull().sum()

Roll_no             0
Name                0
DSBDA_score         0
OOP_score           0
Attendance_count    0
dtype: int64

In [13]:
df

   Roll_no     Name  DSBDA_score  OOP_score  Attendance_count
0        1      Ram       45.000  56.000000                30
1        2     Sham       78.000  78.000000                37
2        3    Pooja       75.375  65.000000                32
3        4     Neha       67.000  45.000000                33
4        5    Priya       66.000  33.000000                33
5        6    Rohit       87.000  78.000000                21
6        7    Manav      132.000  69.000000                29
7        8  Gayatri       36.000  70.000000                34
8        9    Sahil       75.375  62.111111                35
9       10   khushi       92.000  65.000000                29

In [14]:
#detect the outlier
q1=df['DSBDA_score'].quantile(0.25) # gives value below which 25% data lies
q3=df['DSBDA_score'].quantile(0.75) # gives value below which 75% data lies

IQR=q3-q1 # spread of middle data

lower_limit=q1-1.5*IQR
upper_limit=q3+1.5*IQR
print("DSBDA range:", lower_limit, upper_limit)

DSBDA range: 38.5 112.5

In [15]:
# handle the outlier Replace Outliers 
# (Outlier condition: value < 38.5  OR  value > 112.5)

# If value > upper → replaced with upper
# If value < lower → replaced with lower
# Normal values → remain same

df['DSBDA_score']=np.where(df['DSBDA_score']>upper_limit,upper_limit,df['DSBDA_score'])
df['DSBDA_score']=np.where(df['DSBDA_score']<lower_limit,lower_limit,df['DSBDA_score'])

In [16]:
df # (manav- dsbda replace with upper limit)

   Roll_no     Name  DSBDA_score  OOP_score  Attendance_count
0        1      Ram       45.000  56.000000                30
1        2     Sham       78.000  78.000000                37
2        3    Pooja       75.375  65.000000                32
3        4     Neha       67.000  45.000000                33
4        5    Priya       66.000  33.000000                33
5        6    Rohit       87.000  78.000000                21
6        7    Manav      112.500  69.000000                29
7        8  Gayatri       38.500  70.000000                34
8        9    Sahil       75.375  62.111111                35
9       10   khushi       92.000  65.000000                29

In [17]:
# OOP
q1= df['OOP_score'].quantile(0.25)
q3 = df['OOP_score'].quantile(0.75)

IQR = q3-q1

lower_limit = q1 - 1.5 * IQR
upper_limit = q3+ 1.5 * IQR

print("OOP range:", lower_limit, upper_limit)

OOP range: 39.19444444444444 88.08333333333333

In [18]:
df['OOP_score'] = np.where(df['OOP_score'] > upper_limit, upper_limit, df['OOP_score'])
df['OOP_score'] = np.where(df['OOP_score'] < lower_limit, lower_limit, df['OOP_score'])

In [19]:
df # (priya- oop replace with lower limit)

   Roll_no     Name  DSBDA_score  OOP_score  Attendance_count
0        1      Ram       45.000  56.000000                30
1        2     Sham       78.000  78.000000                37
2        3    Pooja       75.375  65.000000                32
3        4     Neha       67.000  45.000000                33
4        5    Priya       66.000  39.194444                33
5        6    Rohit       87.000  78.000000                21
6        7    Manav      112.500  69.000000                29
7        8  Gayatri       38.500  70.000000                34
8        9    Sahil       75.375  62.111111                35
9       10   khushi       92.000  65.000000                29

Apply Transformation

In [20]:
# log Tranformation
df['DSBDA_log']=np.log(df['DSBDA_score'])
print(df)

   Roll_no     Name  DSBDA_score  OOP_score  Attendance_count  DSBDA_log
0        1      Ram       45.000  56.000000                30   3.806662
1        2     Sham       78.000  78.000000                37   4.356709
2        3    Pooja       75.375  65.000000                32   4.322476
3        4     Neha       67.000  45.000000                33   4.204693
4        5    Priya       66.000  39.194444                33   4.189655
5        6    Rohit       87.000  78.000000                21   4.465908
6        7    Manav      112.500  69.000000                29   4.722953
7        8  Gayatri       38.500  70.000000                34   3.650658
8        9    Sahil       75.375  62.111111                35   4.322476
9       10   khushi       92.000  65.000000                29   4.521789

In [21]:
# normalization
df['DSBDA_norm']=(df['DSBDA_score'] - df['DSBDA_score'].min()) / (df['DSBDA_score'].max() - df['DSBDA_score'].min())
print(df)

   Roll_no     Name  DSBDA_score  OOP_score  Attendance_count  DSBDA_log  \
0        1      Ram       45.000  56.000000                30   3.806662
1        2     Sham       78.000  78.000000                37   4.356709
2        3    Pooja       75.375  65.000000                32   4.322476
3        4     Neha       67.000  45.000000                33   4.204693
4        5    Priya       66.000  39.194444                33   4.189655
5        6    Rohit       87.000  78.000000                21   4.465908
6        7    Manav      112.500  69.000000                29   4.722953
7        8  Gayatri       38.500  70.000000                34   3.650658
8        9    Sahil       75.375  62.111111                35   4.322476
9       10   khushi       92.000  65.000000                29   4.521789

   DSBDA_norm
0    0.087838
1    0.533784
2    0.498311
3    0.385135
4    0.371622
5    0.655405
6    1.000000
7    0.000000
8    0.498311
9    0.722973

In [22]:
#  Standarization
mean_value = df['DSBDA_score'].mean()
print(mean_value)

# Values around mean → near 0 
# Above mean → positive 
# Below mean → negative

df['DSBDA_scaled'] = (df['DSBDA_score'] - df['DSBDA_score'].mean()) / df['DSBDA_score'].std()
print(df)

73.675
   Roll_no     Name  DSBDA_score  OOP_score  Attendance_count  DSBDA_log  \
0        1      Ram       45.000  56.000000                30   3.806662
1        2     Sham       78.000  78.000000                37   4.356709
2        3    Pooja       75.375  65.000000                32   4.322476
3        4     Neha       67.000  45.000000                33   4.204693
4        5    Priya       66.000  39.194444                33   4.189655
5        6    Rohit       87.000  78.000000                21   4.465908
6        7    Manav      112.500  69.000000                29   4.722953
7        8  Gayatri       38.500  70.000000                34   3.650658
8        9    Sahil       75.375  62.111111                35   4.322476
9       10   khushi       92.000  65.000000                29   4.521789

   DSBDA_norm  DSBDA_scaled
0    0.087838     -1.326097
1    0.533784      0.200013
2    0.498311      0.078618
3    0.385135     -0.308690
4    0.371622     -0.354936
5    0.655405      0.616225
6    1.000000      1.795491
7    0.000000     -1.626694
8    0.498311      0.078618
9    0.722973      0.847453